name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Set up Upx
      run: |
        sudo apt update
        sudo apt install -y upx

    - name: Build
      run: |
        make all
        upx --lzma --best yuhaiin
        upx --lzma --best yh

    - name: Test
      run: make vet

    - name: upload
      uses: actions/upload-artifact@v2
      with:
        name: output
        path: |
          yuhaiin
          yh