name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    # - name: Set up Upx
    #   run: |
    #     sudo apt update
    #     sudo apt install -y upx

    - name: Build
      run: |
        make all
        upx --lzma --best yuhaiin
        upx --lzma --best yh
        upx --lzma --best yuhaiin.exe
        upx --lzma --best yh.exe

    - name: Test
      run: make vet

    - name: upload_linux
      uses: actions/upload-artifact@v2
      with:
        name: output_linux_amd64
        path: |
          yuhaiin
          yh

    - name: upload_windows
      uses: actions/upload-artifact@v2
      with:
        name: output_windows_amd64
        path: |
          yuhaiin.exe
          yh.exe